// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

/* //old IGV
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFDpec10MV6WsS67kxzGrZmWGs1uEAvk',
    appId: '1:273708662583:android:02094a45c362900a7264b2',
    messagingSenderId: '273708662583',
    projectId: 'unident-83c30',
    storageBucket: 'unident-83c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbKJilEYd-6xDfFVcbNA4ivlQRCKBqdbs',
    appId: '1:273708662583:ios:4373b06ec474338d7264b2',
    messagingSenderId: '273708662583',
    projectId: 'unident-83c30',
    storageBucket: 'unident-83c30.appspot.com',
    iosBundleId: 'com.pacienti.unident',
  );
*/

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );


}

/*
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCecDEJz-Tj59BpR9onyD9YyHIeneyFv4k',
    appId: '1:883769903738:android:6afa4a1a927eb86fad89c3',
    messagingSenderId: '883769903738',
    projectId: 'myunident',
    storageBucket: 'myunident.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGF7i6ypQk5p-K5E_AxyG58o6yBmx0E4',
    appId: '1:883769903738:ios:c2088dfba83e27d0ad89c3',
    messagingSenderId: '883769903738',
    projectId: 'myunident',
    storageBucket: 'myunident.appspot.com',
    iosBundleId: 'com.pacienti.unident',
  );
}
*/
